### ISSUE TITLE
Adding "Bar count"

### ISSUE THREAD

**Issue by mcarquigny** [Unreal-Dan/RekordBoxSongExporter#16]
Hey there ! 
This launcher is awesome, and works flawlessly (latest release and up-to-date RB).

By seeing the addition of the realtime BPM, I wondered if it would be possible to read the current bar count ? Per deck, or for the Master deck would be incredible.

![image](https://user-images.githubusercontent.com/55687024/170268273-05d020cb-76bc-4527-aeb5-70f63058d3f5.png)

This would open up some crazy possibilities, like visual show automation or third-party software sync !

**Comment by Unreal-Dan** [comment]
I can definitely look into this, what kind of information are you looking to get?  

Say I added ```%rt_deck1_barcount%``` and it would be 75.1 ? 

or ```%rt_master_barcount%``` to get the master?

These would update each time the barcount changes, which could be quite fast and could begin to cause performance issues since it's writing to a file each time.

**Comment by mcarquigny** [comment]
For automation purposes, I think that `%rt_master_barcount%` would be the best choice, as it would allow to trigger stuff with simple conditions like `if (masterTrack === 'trackA' && masterBarcount === 75.1)`. But there may be some use cases I can't think of for deck-per-deck barcount !

I was thinking about performance issues last night. 
For what I understand you're not polling/wrinting data every N ms, but listening to function calls that update values directly ?
For fast songs like 190bpm it would result in a disk write every ~300ms but adding it with the others `%rt_*` writes, I agree that it may start to cause trouble.
To avoid that, my best bed would be to write to somethink like a UDP socket instead of disk, at least for all 'realtime' data ?

But that's twisting your project to be something completely different from what you intended, and I'm feeling terrible to ask for this 😅

**Comment by Unreal-Dan** [comment]
> For automation purposes, I think that %rt_master_barcount% would be the best choice, as it would allow to trigger stuff with simple conditions like if (masterTrack === 'trackA' && masterBarcount === 75.1). But there may be some use cases I can't think of for deck-per-deck barcount !

If I were to add any kind of barcount then I would add all 5 tags, decks 1 through 4 and the master. The 'master' tag would just use my existing infrastructure to detect which deck is the master then return the information for the respective deck (so the other 4 tags are effectively necessary in order to make the master tag).

> For what I understand you're not polling/wrinting data every N ms, but listening to function calls that update values directly ?

I am hooking directly into functions that rekordbox uses, the trick is picking the correct function.  I'm not sure of a function that gets called every 0.1bars and I would need to find it if it existed.  Just because I am hooking rekordbox functions doesn't necessarily mean it's faster or more efficient than just polling. There is a point at which hooking will cause a noticeable performance loss and just running a separate thread to poll the data would be more efficient, this would happen if the target function was used heavily.

With regards to which function I can hook... I do see the render function for the waveform which seems to render the ```%dBars``` text shown in your screenshot. The problem is it's generally bad to do other things inside rendering threads so hooking that function then writing to a file from my hook could cause issues with the rendering of Rekordbox, or it might work without issues.

> For fast songs like 190bpm it would result in a disk write every ~300ms but adding it with the others %rt_* writes, I agree that it may start to cause trouble.

I didn't actually do the math, thanks for that, that doesn't sound too bad to be honest.  I could see a slower PC starting to struggle if it was already doing a lot of work. I will definitely try out some hooks and see.

> To avoid that, my best bed would be to write to somethink like a UDP socket instead of disk, at least for all 'realtime' data ?

If you want to catch your own updates, you can listen to a network socket then enable server mode in the launcher and it will send all of the updates to a socket for the given network address, the server is designed to create that listening network socket and decode the information then write it to files. If you wanted to create your own endpoint you could use the server code as a starting point, any language that can create a listening tcp socket would work. Using UDP might offer some benefits but I would say TCP is the better option and won't cause any performance issues.

----

At any rate I will poke around and see if there's a way I can hook the bars, are you familiar with C++ or do you have visual studio?  I can't guarantee I will release anything unless it works well, but I can most likely put together a branch that you can compile yourself and/or tweak to your liking. 

Add me on discord if you're interested in putting together your own custom build Daniel # 8135

**Comment by mcarquigny** [comment]
I've been developing for a long time, but I've worked exclusively on web and server tooling, so I'm a bit lacking in system and low-level knowledge. But I have access to a good editor, and it's never too late to learn.
I've added you on discord, and I'll start playing with the project in the meantime.
Thanks again for your availability!
