### ISSUE TITLE
Version 6.6.8?

### ISSUE THREAD

**Issue by piregg** [Unreal-Dan/RekordBoxSongExporter#19]
Does anyone know if version 6.6.8 is working with this please? I'm currently still on version 6.6.4

**Comment by Unreal-Dan** [comment]
You can install the new version without uninstalling the old, just make sure to untick the box in the installer that says "uninstall previous version".  

That way you would have both 6.6.4 and 6.6.8 installed, just in case.

I'm fairly certain it still works with 6.6.8 otherwise I'd be getting notifications from people, if it doesn't feel free to come back here and let me know so I can fix it.

Note, only RBSE version 6.7+ will work with future versions of Rekordbox because that is when "future proofing" was added to protect against updates.
