### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by fivefortyfour** [Unreal-Dan/RekordBoxSongExporter#2]
I've read the notes but I don't get it?  What do I run to start the launcher? Am I supposed to compile it first? I am just a windows user, not a developer...

**Comment by fivefortyfour** [comment]
aaah. found the zip file and got them now...  just need to install VCRUNTIME140.dll now....

**Comment by Unreal-Dan** [comment]
You need Microsoft Visual C++ Redistributable, a package from microsoft that provides runtime libraries for programs built with visual studio.

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

You should get the latest package for 2015, 2017, and 2019 (it's all combined), get both the x86 and x64 just to be safe.

Most people already have these packages installed that's why I didn't mention anything about them, maybe I'll add a note.

**Comment by Unreal-Dan** [comment]
I remembered I can switch a setting in visual studio to static link those libraries you were missing, that would prevent that issue from happening to anybody else - at the cost of slightly larger binaries. Definitely a win, thanks for bringing this up (even if it was a source of a headache).

**Comment by fivefortyfour** [comment]
No problem!  I had a few install problems. Tried both x86 and x64. At one point RB6 wouldn't open, then gave an error... Uninstalled then re-installed etc... worked eventually. Was worried I'd broken RB6 !

Will try the update you did too. Looks good, thank you
