### ISSUE TITLE
Realtime master BPM not working on 6.7.0

### ISSUE THREAD

**Issue by rmonier** [Unreal-Dan/RekordBoxSongExporter#22]
Hi @Unreal-Dan 

On Windows 11 the `%rt_master_bpm%` is not updated in realtime with RBSE v3.8, rekordbox v6.7.0. Not sure if it's linked to my OS version or not.

I tried to get a debug trace from the `olvc_callback` , but the callback is never triggered (so `bpm_callback` is never triggered too). However it seems that `djengineIF::setTempo` and `djplay::DeviceComponent::operateLongValueChange` sigs are correctly located by the scan.

The BPM is only updated when the `UPDATE_TYPE_MASTER` deck update type is pushed to the queue.

*On a side note, thank you for this project, it's awsome! I'm currently working on a little [feature branch](https://github.com/rmonier/RekordBoxSongExporter/tree/feature/link) to integrate [Ableton Link](https://github.com/Ableton/Link) to it. It's still an experimentation, but I plan to integrate the realtime BPM to a Link session, as the current implementation in rekordbox forces the user to beat-sync all the decks and deactivate the BPM control on them.*

**Comment by Unreal-Dan** [comment]
Ah I never quite tested that part when I fixed it for 6.7.0

I'll take a look later when I get home it's probably just a signature that needs updating as the logic should be pretty unbreakable as long as the hooks are working.

Apologies the codebase is a mess this project was just as much a research project as it was a tool for my friends and I.

I can't remember exactly how the realtime master bpm is triggered but I do know there are several obsolete components and at least one obsolete hook that still exist in the code but do nothing due to a better method being implemented alongside it.

So it's possible it doesn't originate from olvc callback but I can't confirm right now as I'm not at my PC. 

I will look later and confirm, if you want to add me on discord Daniel#8135 I'll be happy to answer any questions you might have.

**Comment by Unreal-Dan** [comment]
Also tip if you compile in debug mode it will open a console and log things

**Comment by rmonier** [comment]
I think it's the olvc callback which is used for the BPM, as it's the one initialized in the `mainThread` function with `init_olvc_callback()`. The obsolete hook for the master BPM might be in the `SemitoneKeyControl.cpp`, but the `DC_OLVC_SIG` is the same as the one in `OlvcCallback.cpp`, so as you said it's probably a signature change in 6.7.0.

And yes I used the debug mode to set some `info` traces!

**Comment by Unreal-Dan** [comment]
sorry for the delay, it was indeed just a signature that needed updating. Fixed here: https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.8.1
