### ISSUE TITLE
Track progress, length and possible waveform

### ISSUE THREAD

**Issue by TheExiledCat** [Unreal-Dan/RekordBoxSongExporter#25]
Hi, would it be possible to also export the data for the total track length and current track position in both seconds/minutes and possibly in beats and bars. This would be very handy for people using this application to make their own dj hardware (i am making my own turntable).

I also figured it might be possible to export the wav related to the song or a compressed version of it so it can be showcased on a screen.

**Comment by Unreal-Dan** [comment]
You know there's actually a whole bunch of tags that aren't documented in the readme, specifically you want the tags that start with rt_ meaning realtime.

There is rt_bpm tags listed in the readme, but what isn't actually listed is these other tags:

```
  if (format.find("%rt_master_bpm%") != string::npos)     { format_tags |= TAG_RT_MASTER_BPM; }
  if (format.find("%rt_deck1_time%") != string::npos)     { format_tags |= TAG_RT_DECK1_TIME; }
  if (format.find("%rt_deck2_time%") != string::npos)     { format_tags |= TAG_RT_DECK2_TIME; }
  if (format.find("%rt_deck3_time%") != string::npos)     { format_tags |= TAG_RT_DECK3_TIME; }
  if (format.find("%rt_deck4_time%") != string::npos)     { format_tags |= TAG_RT_DECK4_TIME; }
  if (format.find("%rt_master_time%") != string::npos)    { format_tags |= TAG_RT_MASTER_TIME; }
  if (format.find("%rt_deck1_total_time%") != string::npos) { format_tags |= TAG_RT_DECK1_TOTAL_TIME; }
  if (format.find("%rt_deck2_total_time%") != string::npos) { format_tags |= TAG_RT_DECK2_TIME; }
  if (format.find("%rt_deck3_total_time%") != string::npos) { format_tags |= TAG_RT_DECK3_TOTAL_TIME; }
  if (format.find("%rt_deck4_total_time%") != string::npos) { format_tags |= TAG_RT_DECK4_TOTAL_TIME; }
  if (format.find("%rt_master_total_time%") != string::npos) { format_tags |= TAG_RT_MASTER_TOTAL_TIME; }
  if (format.find("%rt_master_deck%") != string::npos) { format_tags |= TAG_RT_MASTER_DECK; }
```

rt_master_bpm would be the realtime bpm of the master deck, updated in realtime as it changes, for example.

rt_deck1_total_time would be the total number of seconds? (I forget which unit it is) in the deck1 track, and it will update in realtime as it changes.

rt_deck1_time would be the current playhead position (in seconds? whatever unit it's same as total_time)

So you should be able to use the rt_deck1_total_time + rt_deck1_time to extrapolate a play position + total time of the 1st deck. Then from there you can perform some division to extrapolate the beats/bars/etc.

As for exporting a waveform I definitely can't do that, but a solution I can suggest is use a separate program (idk google for something) to process all of your tracks into images of their waveform and then have a library of waveforms indexed by the track ID. Then you can use the current track ID to lookup the waveform, then offset it based on the time and total_time of the track. But other than that I'm not sure how you could achieve the waveform.

Also, ideally, what you'd want to do is modify the server program (or write your own server program) to parse the server messages from the client, rather than parsing the output files as they update because that would be expensive. 

That would allow you to parse the time updates in realtime with the server software, then you could translate that into whatever you need to do.

Let me know how this goes and if it serves your purpose.

**Comment by TheExiledCat** [comment]
This is perfect thank you!
