### ISSUE TITLE
Unexpected rekordbox crash

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#3]
Hi Dan,

i've been using it a lot, it's great but today i had 2 crashes under 2h. I installed the latest firmware today just before streaming; do you think it could be related? I've never had an issue before that (crap!)

Thanks

**Comment by Unreal-Dan** [comment]
Interesting, try using an older version in the meantime.  Something before 2.2 because that's when things changed quite a bit and might be causing you problems.

Which version of rekordbox were you crashing on? 650/585?

Which version of RBSE were you crashing on?

Which OS are you on?  

Did the crashes happen while you were transitioning songs, or just randomly while songs were playing?

Also if rekordbox generated minidump files those might help me track it down.

You can find the dumps in ...\AppData\Roaming\Pioneer\rekordbox\Crashes

**Comment by frank-h-w** [comment]
I'm on rekordbox 650, RBSE 2.1, Win10 64bit.
It was a random crash, twice on stream and it was after 2 OBS reboot. I'm not sure if its the interaction of OBS and the .txt files or it was rekordbox.

I did change the firmware of the board but I don't see how that would interact with your hack! Dump files here (zipped the two of the two events on saturday)
[dumpfiles.zip](https://github.com/Unreal-Dan/RekordBoxSongExporter/files/6059111/dumpfiles.zip)

**Comment by Unreal-Dan** [comment]
Yeah I don't see how the firmware change would interact with the hack either, the hack only touches Rekordbox and doesn't care about the controller at all.

If you're crashing on sub-2.2 versions then try moving to at least 2.2 a lot changed in that version and the entire approach was switched up for a different approach that allows me to retrieve more song information. That's why I suggested a pre-2.2 version before, I assumed you were crashing on something past that version.

The latest version 2.3 is the most stable and has the most fixes, I would go with that.

If you still crash on post-2.2 then come back and let me know.  

If 2.3 works without any issues then any feedback would still be appreciated so I know there isn't an issue to track down. 

Thanks again for reporting this, and thanks for using the software, I'm glad I can make a difference.

**Comment by frank-h-w** [comment]
Let me try it out this week! Question, the new metadata, specifically regarding BPM, is it the deck's BPM or the track's base BPM?

**Comment by Unreal-Dan** [comment]
it's the unaltered original track BPM, deck bpm may come in the future!

**Comment by Unreal-Dan** [comment]
I'm going to close this now, if you have any further crashes with the latest version just open another ticket. Thanks.

**Comment by frank-h-w** [comment]
Worked fine except a bit of sluggish performance but I don't think it's
your hack CPU usage was high because of obs and other stuff so yes close it
