### ISSUE TITLE
Lag between exporter "program screen" vs the ".txt" files - version 3.0

### ISSUE THREAD

**Issue by frank-h-w** [Unreal-Dan/RekordBoxSongExporter#6]
Hi Dan,

I've been using the new one (and the previous 2.5 version) a lot lately in server mode and i've hit an issue. As I cue new songs, i see the software receive the feed but the .txt output file is lagged 1-2 songs behind. 

Let me know what else i need to provide to help you debug.

Frank

**Comment by Unreal-Dan** [comment]
Which file are you talking about?  

The 'offset' field controls how many tracks pass till the respective file is updated.

The 'RotatingTrackList' contains the 2nd to 8th tracks, so a rotating list of 5 tracks that is offset by 2.

If you want it to not lag behind at all then change the offset to 0.

The 'CurTrackTitle' and 'CurTrackArtist' should not be lagging behind at all.  

If this isn't what you're experiencing then post a copy of your config.ini for me

**Comment by frank-h-w** [comment]
ahhhhhhh ok so its the offset perhaps. Other question, the tracklist, does
it have to be in append mode? Mine only had 1 entry after my set :)(

Frank

**Comment by Unreal-Dan** [comment]
Yes Append makes it attach to the bottom of the file. 

Replace makes it rewrite the single line in the file

And prepend inserts it at the top of the file.

Give a read over the updated readme on the main page of the project, I go into detail about all the new UI and settings and it should solve any confusions you have :)

If anything is unclear then please let me know, I'm not the best at documentation and it's hard to read your own documentation and tell where it's lacking in information or explanation.

Also if any of the information doesn't seem to line up with how the software is working then please let me know, it's not impossible that there's a bug.

**Comment by Unreal-Dan** [comment]
I believe you may have actually found a bug, because I tried setting the TrackList to 'prepend' mode which should prepend the tracks no problem... And it only ever has 1 track in the file.

Apologies I'm going to see if I can fix this right now.

**Comment by frank-h-w** [comment]
No worries!

**Comment by Unreal-Dan** [comment]
Okay I remember now why it's behaving this way, prepend mode is a tricky one.

The problem occurs specifically when running in 'Prepend' mode with the 'Max Lines' set to 0. 

One would think this means 'prepend' with unlimited lines but I never actually finished that feature because it would have to work differently from prepend with a fixed line count.

The reason this is a problem is because of how prepending to files works, there is no trick to 'insert' text at the start of a file.

The only way to prepend to a file is to actually re-write the entire file so I just cut corners and made the 'max_lines' of 0 actually just a value of 1, this meant you could not run prepend mode with 'unlimited lines' because each time you prepend to the file you would need to read the entire file into memory which could result in Rekordbox running out of memory and crashing.

However... I've done some research and this is definitely possible if we use a temporary file and just copy over chunks of the old file.

I have repaired prepend mode with 'max lines' of 0 in the latest version 3.1 I am releasing now, give that a try and let me know.

**Comment by frank-h-w** [comment]
Hey Dan,

Works great now !

I had an unrelated question, is there a way for me to check the different
function variable names used by rekordbox internally? I'm trying to midi
map functions that aren't midi-mappable (because they don't natively allow
it) but i'Ve found on a forum someone that managed to do it and it works!

Problem is, I cannot seem to find the "other" function names.  An example
below the " CFXSubParameter" is an actual function in rekordbox and I
managed to remap it (even if it wasn't available in the MIDI list) to a
knob that I don't use.
I want to find the "sub" parameters for FX in single mode. Would you be
able to point me in the right direction to find them? They are
cerncled below, it's the subparameter1 and 2 debt and it seems to be
another 2 "sub" effect trigger on/off.

thanks for the amazing work as usual, the new version works flawlessly.

Frank

[image: ScreenHunter_264 Aug. 09 17.28.jpg]
[image: ScreenHunter_265 Aug. 09 17.29.jpg]
