### ISSUE TITLE
RBSE Version 3.4 - Tracklist sometimes gets updates, sometimes not

### ISSUE THREAD

**Issue by MartinTicTacTrance** [Unreal-Dan/RekordBoxSongExporter#9]
Hello,

with the new version 3.4 I have issues with the tracklist getting updates. Normally I use the MASTER button to tell the software that the new track is being played. It worked good with the previous version, with this version not any more.

Sometimes it notifices a new track is being played, sometimes it totally ignores this.
Did you change the logics in this mechanics?

Thanks!

**Comment by Unreal-Dan** [comment]
Thanks for this report I will look into it, I didn't change any logic surrounding this mechanism so that is quite strange.  

Edit: Okay I think I found the problem, seems like there was more changes in 6.6.1 that I needed to account for.  I didn't notice them when I tested it quickly, that's my mistake.

**Comment by Unreal-Dan** [comment]
Apologies this was just a big oversight on my part, solved in 3.41 here

https://github.com/Unreal-Dan/RekordBoxSongExporter/releases/tag/3.41
